[package]
name = "kobayashi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "normalize_stfc_data"
path = "src/bin/normalize_stfc_data.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
